export const groupData = {
    userPerfil: [
        { label: 'Funcionário', value: 'funcionario' },
        { label: 'Aluno', value: 'aluno' },
        { label: 'Interessado', value: 'interessado' },
    ],
    userCivil: [
        { label: 'Solteiro', value: 'Solteiro' },
        { label: 'Casado', value: 'Casado' },
        { label: 'Separado', value: 'Separado' },
        { label: 'Divorciado', value: 'Divorciado' },
        { label: 'Viúvo', value: 'Viúvo' },
        { label: 'União estável', value: 'União estável' }
    ],
    userEscolaridade: [
        { label: 'Ensino fundamental (incompleto)', value: 'Ensino fundamental (incompleto)' },
        { label: 'Ensino fundamental', value: 'Ensino fundamental' },
        { label: 'Ensino médio', value: 'Ensino médio' },
        { label: 'Superior (Graduação)', value: 'Superior (Graduação)' },
        { label: 'Pós-graduação', value: 'Pós-graduação' },
        { label: 'Mestrado', value: 'Mestrado' },
        { label: 'Doutorado', value: 'Doutorado' },
    ],
    typeStatus: [
        { label: 'ativo', value: 1 },
        { label: 'inativo', value: 0 },
    ],
    typeYesOrNo: [
        { label: 'sim', value: 1 },
        { label: 'não', value: 0 },
    ],
    groupForeigner: [
        {
            label: 'Estrangeiro sem CPF',
            value: true
        },
    ],
    userNationality: [
        { label: 'Brasileira Nata', value: 'Brasileira Nata' },
        { label: 'Brasileira por Naturalização', value: 'Brasileira por Naturalização' },
        { label: 'Estrangeira', value: 'Estrangeira' },
    ],
    racaCor: [
        { label: 'Prefiro não declarar', value: 'Prefiro não declarar' },
        { label: 'Branco', value: 'Branco' },
        { label: 'Preto', value: 'Preto' },
        { label: 'Pardo', value: 'Pardo' },
        { label: 'Amarelo', value: 'Amarelo' },
        { label: 'Indígena', value: 'Indígena' },
    ],
    gender: [
        { label: 'Masculino', value: 'Masculino' },
        { label: 'Feminino', value: 'Feminino' },
        { label: 'Outro', value: 'Outro' },
        { label: 'Prefiro não informar', value: 'Prefiro não informar' },
    ],
    userDisability: [
        { label: 'Sim', value: 'Sim' },
        { label: 'Não', value: 'Não' },
        { label: 'Não dispõe de informação', value: 'Não dispõe de informação' },
    ],
    deficiencyTypes: [
        { label: 'Deficiência visual', value: 'Deficiência visual' },
        { label: 'Deficiência intelectual', value: 'Deficiência intelectual' },
        { label: 'Deficiência múltipla ', value: 'Deficiência múltipla ' },
        { label: 'Surdez e deficiência auditiva', value: 'Surdez e deficiência auditiva' },
        { label: 'Deficiência auditiva', value: 'Deficiência auditiva' },
        { label: 'Deficiência fisica e motora', value: 'Deficiência fisica e motora' }
    ],
    autismTypes: [
        { label: 'Transtorno global do desenvolvimento (TGD)', value: 'Transtorno global do desenvolvimento (TGD)' },
        { label: 'Transtorno do espectro autista (TEA)', value: 'Transtorno do espectro autista (TEA)' },
    ],
    superGifted: [
        { label: 'Altas habilidades/superdotação', value: 'Altas habilidades/superdotação' },
    ],
    origemEnsinoMedio: [
        { label: 'Pública', value: 'Pública' },
        { label: 'Privada', value: 'Privada' }
    ],
    reasonsDroppingOut: [
        { label: 'Pessoal', value: 'Pessoal' },
        { label: 'Financeiro', value: 'Financeiro' },
        { label: 'Insatisfação', value: 'Insatisfação' },
        { label: 'Turma cancelada', value: 'Turma cancelada' },
        { label: 'Reprovação', value: 'Reprovação' },
        { label: 'Profissional', value: 'Profissional' },
        { label: 'Saúde', value: 'Saúde' },
        { label: 'Dificuldade', value: 'Dificuldade' },
        { label: 'Não quis informar ', value: 'Não quis informar ' },
    ],
    levelEmployee: [
        { label: 'Junior', value: 'Junior' },
        { label: 'Pleno', value: 'Pleno' },
        { label: 'Sênior', value: 'Sênior' },
        { label: 'Instrutor', value: 'Instrutor' },
        { label: 'Especialista A', value: 'Especialista A' },
        { label: 'Especialista B', value: 'Especialista B' },
        { label: 'Especialista C', value: 'Especialista C' },
        { label: 'Especialista D', value: 'Especialista D' },
        { label: 'Especialista E', value: 'Especialista E' },
        { label: 'Especialista F', value: 'Especialista F' },
        { label: 'Mestre A', value: 'Mestre A' },
        { label: 'Mestre B', value: 'Mestre B' },
        { label: 'Mestre C', value: 'Mestre C' },
        { label: 'Mestre D', value: 'Mestre D' },
        { label: 'Mestre E', value: 'Mestre E' },
        { label: 'Mestre F', value: 'Mestre F' },
        { label: 'Doutor A', value: 'Doutor A' },
        { label: 'Doutor B', value: 'Doutor B' },
        { label: 'Doutor C', value: 'Doutor C' },
        { label: 'Doutor D', value: 'Doutor D' },
        { label: 'Doutor E', value: 'Doutor E' },
        { label: 'Doutor F', value: 'Doutor F' }
    ],
    area: [
        { label: 'Financeiro', value: 'Financeiro' },
        { label: 'Biblioteca', value: 'Biblioteca' },
        { label: 'TI - Suporte', value: 'TI - Suporte' },
        { label: 'RH', value: 'RH' },
        { label: 'Marketing', value: 'Marketing' },
        { label: 'Atendimento/Recepção', value: 'Atendimento/Recepção' },
        { label: 'Secretaria', value: 'Secretaria' },
        { label: 'Administrativo', value: 'Administrativo' },
        { label: 'Diretoria', value: 'Diretoria' },
        { label: 'Acadêmica', value: 'Acadêmica' },
    ],
    banks: [
        { label: 'Itaú', value: 'Itau' },
        { label: 'Bradesco', value: 'Bradesco' }
    ],
    typesAccount: [
        { label: 'Conta Corrente', value: 'Conta Corrente' },
        { label: 'Conta salário', value: 'Conta salário' },
        { label: 'Conta poupança', value: 'Conta poupança' }
    ],
    formaIngresso: [
        { label: 'Redação Online', value: 'Redação Online' },
        { label: 'Nota do Enem', value: 'Nota do Enem' },
        { label: 'Segunda Graduação', value: 'Segunda Graduação' },
        { label: 'Trânsferência', value: 'Trânsferência' },
        { label: 'Curso de extensão', value: 'Curso de extensão' },
        { label: 'Destrancamento de matrícula', value: 'Destrancamento de matrícula' },
    ],
    paymentForm: [
        { label: 'Pagamento estendido', value: 'Pagamento estendido' },
        { label: 'PRAVALER', value: 'PRAVALER' },
        { label: 'Boleto', value: 'Boleto' },
        { label: 'Cartão de Crédito', value: 'Cartão de Crédito' },
        { label: 'Ex Aluno 5%', value: 'Ex Aluno' },
    ],

    contactForm: [
        { label: 'WhatsApp', value: 'WhatsApp' },
        { label: 'E-mail', value: 'E-mail' },
        { label: 'Ligação', value: 'Ligação' },
        { label: 'Visita presencial ao Campus (São Paulo)', value: 'Visita presencial ao Campus (São Paulo)' },
    ],
    enrollmentSituation: [
        { label: 'Aguardando início', value: 'Aguardando início' },
        { label: 'Pendente de assinatura do contrato', value: 'Pendente de assinatura do contrato' },
        { label: 'Em andamento', value: 'Em andamento' },
        { label: 'Concluído', value: 'Concluído' },
        { label: 'Curso Finalizado', value: 'Curso Finalizado' },
        { label: 'Turma cancelada', value: 'Turma cancelada' },
        { label: 'Aprovado', value: 'Aprovado' },
        { label: 'Reprovado', value: 'Reprovado' },
        { label: 'Bloq. Online', value: 'Bloq. Online' },
        { label: 'Matrícula cancelada', value: 'Matrícula cancelada' },
        { label: 'Transferido ', value: 'Transferido ' },
        { label: 'Desistente ', value: 'Desistente ' },
        { label: 'Nenhuma', value: 'Nenhuma' },
        { label: 'Trancamento', value: 'Trancamento' },
    ],
    reasonsDroppingOut: [
        { label: 'Pessoal', value: 'Pessoal' },
        { label: 'Financeiro', value: 'Financeiro' },
        { label: 'Insatisfação', value: 'Insatisfação' },
        { label: 'Turma cancelada', value: 'Turma cancelada' },
        { label: 'Reprovação', value: 'Reprovação' },
        { label: 'Profissional', value: 'Profissional' },
        { label: 'Saúde', value: 'Saúde' },
        { label: 'Dificuldade', value: 'Dificuldade' },
        { label: 'Não quis informar ', value: 'Não quis informar ' },
    ]
}