import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Box, ContentContainer, Text } from '../atoms'
import { Carousel } from '../organisms'
import { useAppContext } from '../context/AppContext'
import { icons } from '../organisms/layout/Colors'
import { useEffect, useState } from 'react'
import { menuItems } from '../permissions'
import { useRouter } from 'next/router'
import { getImageByScreen } from '../validators/api-requests'
import { api } from '../api/api'

const inter = Inter({ subsets: ['latin'] })

const backgroundHome = [
   { name: 'slide-1', location: 'https://adm-melies.s3.amazonaws.com/slide-3.jpg' },
   { name: 'slide-2', location: 'https://adm-melies.s3.amazonaws.com/slide-5.jpg' },
]

const menuProfessor = [
   { id: '01', icon: '', text: 'Aulas do dia', to: '/academic/frequency/list', query: true },
   { id: '02', icon: '', text: 'Lançar nota', to: '/academic/studentGrade/list', query: true },
   { id: '03', icon: '', text: 'Atividade Complementar', to: '/', query: false },
   { id: '04', icon: '', text: 'Calendário Acadêmico', to: '/administrative/calendar/calendar', query: false },
   { id: '05', icon: '', text: 'Cronograma', to: '/administrative/classSchedule/list', query: false },
]

const birthDate = [
   { id: '01', name: 'Marcus Silva', day: 1, function: 'Desenvolvedor' },
   { id: '02', name: 'Felipe Bomfim', day: 13, function: 'Suporte' },
   { id: '03', name: 'Fulano Silva', day: 15, function: 'Suporte' },
   { id: '04', name: 'Renato Miranda', day: 5, function: 'Gerente Suporte' }
]

export default function Home() {

   const { user, colorPalette, theme, setLoading } = useAppContext()
   const [menu, setMenu] = useState(menuItems)
   const [imagesList, setImagesList] = useState([])
   const [listBirthDay, setListBirthDay] = useState([])
   let isProfessor = user?.professor === 1 ? true : false;
   const userId = user?.id;

   const router = useRouter();


   const handleImages = async () => {
      setLoading(true)
      try {
         const response = await getImageByScreen('Inicio - Banner rotativo')
         if (response.status === 200) {
            setImagesList(response.data)
         }
      } catch (error) {
         return error
      } finally {
         setLoading(false)
      }
   }


   const handleBirthday = async () => {
      setLoading(true)
      try {
         const response = await api.get(`/user/list/birthdates`)
         if (response.status === 200) {
            setListBirthDay(response?.data)
         }
      } catch (error) {
         return error
      } finally {
         setLoading(false)
      }
   }


   useEffect(() => {
      handleImages(imagesList)
      handleBirthday()
   }, [])


   return (
      <>
         <Head>
            <title>Administrativo Méliès</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta charset="utf-8" />
            <link rel="icon" href="https://adm-melies.s3.amazonaws.com/logo_vermelho_linhas_brancas.svg" />
         </Head>
         <Box sx={{ marginTop: { xs: 0, xm: -8, md: -8, lg: -8 } }}>
            <Box>
               <Box sx={{ display: 'flex', flexDirection: { xs: 'column', xm: 'row', md: 'row', lg: 'row' }, alignItems: 'center', gap: 2 }}>
                  <Text
                     bold
                     veryLarge
                     style={{ padding: { xs: '0', xm: '10px 0px 10px 0px', md: '10px 0px 10px 0px', lg: '10px 0px 10px 0px' }, display: 'flex', gap: 8 }}>
                     Bem-vindo,
                     <Text bold veryLarge style={{ color: colorPalette.buttonColor }}>
                        {user?.nome}!
                     </Text>
                  </Text>
                  <Text bold small>Se liga nas novidades...</Text>
               </Box>
               <Carousel
                  data={imagesList || backgroundHome}
                  style={{
                     backgroundColor: colorPalette.secondary,
                     borderRadius: '8px',
                     boxShadow: `rgba(149, 157, 165, 0.17) 0px 6px 24px`,
                  }}
                  heigth={{ xs: 200, xm: 480, md: 200, lg: 280, xl: 400 }}
                  width={'auto'}
               />
            </Box>
            <ContentContainer style={{ marginTop: '30px', boxShadow: 'none', backgroundColor: 'none', }}>
               <Text bold title={true} sx={{ padding: { xs: '0px 0px 20px 20px', xm: '0px 0px 20px 40px', md: '0px 0px 30px 0px', lg: '0px 0px 20px 80px' } }}>
                  Menu de fácil acesso..</Text>
               {isProfessor ?
                  (<Box sx={{ display: 'flex', gap: 5, justifyContent: 'flex-start', flexWrap: { xs: 'wrap', xm: 'wrap', md: 'wrap', lg: 'wrap' }, display: { xs: 'flex', xm: 'flex', md: 'flex', lg: 'flex' } }}>
                     {menuProfessor?.map((group, index) => {

                        return (
                           <ContentContainer key={`${group}-${index}`} sx={{
                              alignItems: 'center', backgroundColor: colorPalette.buttonColor,
                              width: '200px',
                              transition: '.5s',
                              justifyContent: 'center',
                              "&:hover": {
                                 cursor: 'pointer',
                                 opacity: 0.8,
                                 transform: 'scale(1.1)',
                              }
                           }} onClick={() => {
                              group.query ?
                                 router.push(`${group.to}?id=${userId}`) : router.push(`${group.to}`)
                           }}>
                              <Text bold style={{ color: '#fff', transition: 'background-color 1s', textAlign: 'center' }}>
                                 {group.text}
                              </Text>
                           </ContentContainer>
                        )
                     })}

                  </Box>
                  )
                  :
                  (<Box sx={{ display: 'flex', gap: 5, justifyContent: 'center', flexWrap: { xs: 'wrap', xm: 'wrap', md: 'wrap', lg: 'wrap' }, display: { xs: 'flex', xm: 'flex', md: 'flex', lg: 'flex' } }}>

                     {menu?.map((group, index) =>
                        <ContentContainer key={`${group}-${index}`} sx={{
                           alignItems: 'center', backgroundColor: colorPalette.buttonColor,
                           minWidth: '180px',
                           transition: '.5s',
                           "&:hover": {
                              cursor: 'pointer',
                              opacity: 0.8,
                              transform: 'scale(1.1)',
                           }
                        }} onClick={() => router.push(group.to)}>
                           <Box sx={{ ...styles.icon, backgroundImage: `url(${group?.icon_dark})`, width: group?.text === 'Administrativo' ? 15 : 18, height: group.text === 'Administrativo' ? 24 : 18, filter: 'brightness(0) invert(1)', transition: 'background-color 1s' }} />
                           <Text bold style={{ color: '#fff', transition: 'background-color 1s', }}>
                              {group.text}
                           </Text>
                        </ContentContainer>
                     )}

                  </Box>
                  )
               }
            </ContentContainer>

            <Box sx={{ display: 'flex', flexDirection: 'column', marginTop: 5, justifyContent: 'center', flex: 1, gap: 1 }}>
               <Text large bold style={{ textAlign: 'center' }}>Aniversáriantes - {new Date().toLocaleString('pt-BR', { month: 'long' })} 🎉🎉</Text>
               <Box sx={{ display: 'flex', justifyContent: 'center', flex: 1 }}>
                  {listBirthDay.length > 0 ?
                     <div style={{ borderRadius: '8px', overflow: 'hidden', marginTop: '10px', border: `1px solid ${colorPalette.textColor}`, width: '500px' }}>
                        <table style={{ borderCollapse: 'collapse', width: '100%' }}>
                           <thead>
                              <tr style={{ backgroundColor: colorPalette.buttonColor, color: '#fff', }}>
                                 <th style={{ padding: '8px 10px', fontFamily: 'MetropolisBold', fontSize: '13px' }}>Dia</th>
                                 <th style={{ padding: '8px 10px', fontFamily: 'MetropolisBold', fontSize: '13px' }}>Funcionário</th>
                                 <th style={{ padding: '8px 10px', fontFamily: 'MetropolisBold', fontSize: '13px' }}>Cargo/Função</th>
                              </tr>
                           </thead>
                           <tbody>

                              {listBirthDay?.map((item, index) => {
                                 const date = item?.nascimento?.split('T')[0]
                                 const day = date?.split('-')[2]
                                 return (
                                    <tr key={index}>
                                       <td style={{ padding: '8px 10px', fontSize: '13px', fontFamily: 'MetropolisRegular', color: colorPalette.textColor, textAlign: 'center' }}>{day}</td>
                                       <td style={{ padding: '8px 10px', fontSize: '13px', fontFamily: 'MetropolisRegular', color: colorPalette.textColor, textAlign: 'center' }}>{item?.nome}</td>
                                       <td style={{ padding: '8px 10px', fontSize: '13px', fontFamily: 'MetropolisRegular', color: colorPalette.textColor, textAlign: 'center' }}>{item?.funcao || 'Nenhum(a)'}</td>
                                    </tr>
                                 )
                              })
                              }
                           </tbody>
                        </table>
                     </div>
                     :
                     <Box sx={{ backgroundColor: colorPalette.secondary, padding: '5px 10px' }}>
                        <Text >Não existem aniversáriantes nesse mês</Text>
                     </Box>
                  }
               </Box>
            </Box>
         </Box>
      </>
   )
}

const styles = {
   icon: {
      backgroundSize: 'cover',
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center center',
      width: '15px',
      height: '15px',
      marginRight: '0px',
      backgroundImage: `url('/favicon.svg')`,
   },
   menuIcon: {
      backgroundSize: 'cover',
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center',
      width: 20,
      height: 20,

   },
}