import Head from 'next/head'
import { Box } from '../atoms'
import { useAppContext } from '../context/AppContext'
import { ProtectRoute } from '../context/ProtectRoute'
import { Colors, LeftMenu, UserHeader } from '../organisms'
// import { menuItems } from '../permissions'
import '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { api } from '../api/api'

const PagesRoute = ({ Component, pageProps }) => {

    const { colorPalette } = useAppContext()

    return (
        <>
            <Head>
                <title>Administrativo Méliès</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta charset="utf-8" />
                <link rel="icon" href="https://adm-melies.s3.amazonaws.com/logo_vermelho_linhas_brancas.svg" />
            </Head>
            <ProtectRoute>
                <Box sx={{ ...styles.bodyContainer, backgroundColor: colorPalette.primary }}>
                    <LeftMenu />
                    <UserHeader />
                    <Box sx={{ ...styles.contentContainer, backgroundColor: colorPalette.primary, transition: 'background-color 1s' }}>
                        <Component {...pageProps} />
                    </Box>
                </Box>
            </ProtectRoute>
        </>
    )
}

const styles = {
    bodyContainer: {
        display: "flex",
        minHeight: "100vh",
        flexDirection: "row",
        width: '100%',
    },
    contentContainer: {
        display: "flex",
        width: '100%',
        flexDirection: 'column',
        flex: 1,
        gap: `35px`,
        padding: { xs: `30px 30px 85px 30px`, xm: `25px`, md: `120px 65px`, lg: `120px 65px` },
        paddingBottom: `60px`,
        overflowY: 'hidden',
        marginTop: { xs: `60px`, xm: `0px`, md: `0px`, lg: `0px` }
    },
}

export default PagesRoute;